name: Build tippecanoe artifact

on:
  push:
    branches:
      - main
  schedule:
    - cron: "42 5 * * 0"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install dependencies
        run: sudo apt-get install -y gcc g++ make libsqlite3-dev zlib1g-dev

      - name: build tippecanoe
        run: |
          git clone --depth 1 https://github.com/felt/tippecanoe.git
          cd tippecanoe
          make -j
          tar -czf tippecanoe.tar.gz tile-join tippecanoe tippecanoe-enumerate tippecanoe-decode tippecanoe-json-tool tippecanoe-overzoom

      - name: upload binary
        run: |
          # Use command substitution to assign the version to TAG
          TAG=$(./tippecanoe/tippecanoe --version 2>&1 | grep -oP '\d+\.\d+\.\d+')
          echo "tag: $TAG"

          # Create a (latest) release, ignoring error if it already exists
          gh release create --latest --title "$TAG" "$TAG" || true

          # Upload artifact to the release
          gh release upload "$TAG" tippecanoe/tippecanoe.tar.gz
        env:
          GH_TOKEN: ${{ github.token }}
