name: Build tippecanoe artifact

on:
  push:
    branches:
      - main
  schedule:
    - cron: "42 5 * * 0"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: install dependencies
        run: sudo apt-get install -y gcc g++ make libsqlite3-dev zlib1g-dev

      - name: build tippecanoe
        run: |
          git clone --depth 1 https://github.com/felt/tippecanoe.git
          cd tippecanoe
          make -j
          tar -czf tippecanoe.tar.gz tile-join tippecanoe tippecanoe-enumerate tippecanoe-decode tippecanoe-json-tool tippecanoe-overzoom

      - name: upload binary
        run: |
          TAG=$(curl -s https://api.github.com/repos/felt/tippecanoe/tags | jq -r '.[0].name | sub("[a-zA-Z]";"")')
          gh release create --latest --title "$TAG" "$TAG" || true
          gh release upload "$TAG" tippecanoe/tippecanoe.tar.gz --clobber
        env:
          GH_TOKEN: ${{ github.token }}
