name: Build tippecanoe artifact

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: build tippecanoe
        run: |
          git clone --depth 1 https://github.com/felt/tippecanoe.git
          cd tippecanoe
          make -j
          tar -czf tippecanoe.tar.gz tile-join tippecanoe tippecanoe-enumerate tippecanoe-decode tippecanoe-json-tool tippecanoe-overzoom
          
      - name: upload binary
        uses: actions/upload-artifact@v4
        with:
          name: tippecanoe.tar.gz
          path: tippecanoe.tar.gz
