name: Build tippecanoe artifact

on:
  push:
    branches:
      - main
  schedule:
    - cron: "42 5 * * 1"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: check version
        id: check
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Use command substitution to assign the latest version to TAG
          TAG=$(gh release list --exclude-drafts --exclude-pre-releases -R felt/tippecanoe --json tagName --jq ".[0].tagName")
          echo "TAG = $TAG"
          echo "TAG=$TAG" >> "$GITHUB_OUTPUT"

          gh release view -R michaelkreil/tippecanoe-action "$TAG" 2>&1 > /dev/null 
          IS_NEW_VERSION=$?
          echo "IS_NEW_VERSION = $IS_NEW_VERSION"
          echo "IS_NEW_VERSION=$IS_NEW_VERSION" >> "$GITHUB_OUTPUT"

      - name: build tippecanoe
        if: ${{ steps.check.outputs.IS_NEW_VERSION == '1' }}
        env:
          TAG: ${{ steps.check.outputs.TAG }}
        run: |
          sudo apt-get install -y gcc g++ make libsqlite3-dev zlib1g-dev
          curl -L "https://github.com/felt/tippecanoe/archive/refs/tags/$TAG.tar.gz" | tar xz
          cd "tippecanoe-$TAG"
          make -j
          tar -czf ~/tippecanoe.tar.gz tile-join tippecanoe tippecanoe-enumerate tippecanoe-decode tippecanoe-json-tool tippecanoe-overzoom

      - name: upload binary
        if: ${{ steps.check.outputs.IS_NEW_VERSION == '1' }}
        env:
          TAG: ${{ steps.check.outputs.TAG }}
          GH_TOKEN: ${{ github.token }}
        run: |
          # Create a (latest) release, ignoring error if it already exists
          gh release create --latest --title "$TAG" "$TAG" || true

          # Upload artifact to the release
          gh release upload "$TAG" ~/tippecanoe.tar.gz
